### ISSUE TITLE
Adjust results ordering based on popularity (backlinks)

### ISSUE THREAD

**Issue by chamalis** [ahmia/ahmia-site#30]
Include a popularity metrics algorithm, that will have some influence on the results ordering. 

This will use the backlinks from onion addresses. If spam link farmers are detected, we could use some sort of detection mechanism to reduce the influence of those spam websites.

We have to find an appropriate formula to combine that rating with the Elasticsearch's ordering score that's already applied.

Compare with the current results to find out if we managed to improve results ordering.

**Comment by chefarov** [comment]
Current results are not great. To improve them, I would suggest moving towards these directions:
* Try to count backlinks from www as well. That needs research, I am not sure if feasible (e.g through duckduckgo).
* Change algorithm to count score for each page, not each domain.
* Calculate (at runtime) a third score with lower influence, that is PagePopScore of each of the results, considering the backlinks from only the result pages.
