### ISSUE TITLE
Blacklist

### ISSUE THREAD

**Issue by austinsonger** [ahmia/ahmia-site#64]
Where is the blacklist of hashes at?

I'm trying to make a tool that a person enters in a Onion URL that automatically hashes it and then searches that you have generates on your website.

**Comment by chefarov** [comment]
I believe this is what you are looking for https://ahmia.fi/blacklist/banned/

**Comment by austinsonger** [comment]
Yeah I know, but is it in your repo or anything? IT would be easier to search a document in a repo instead of scraping a webpage.

**Comment by chefarov** [comment]
It's dynamically generated list, that's updated and saved in Elasticsearch.
It's very easy to parse, just split on whitespace or newline
