### ISSUE TITLE
Consider Updating?

### ISSUE THREAD

**Issue by AlexanderMaxRanabel** [ahmia/ahmia-site#88]
From what i see the versions of dependencies you guys are using extremly outdated versions of dependincies.
Python 3.6 opposed 3.12
Django 5.0 opposed to 1.11
Elastic 6 opposed to 8
If there is a particular choice behind this choice(Assuming later versions dont work nicely with Tor) i would love to be informed because i am actively considering contributing to this project.

**Comment by samip5** [comment]
I think the main thing is that because it works, and cannot be bothered to upgrade.

The fact that Django is so old is annoying, but when I last tried to upgrade it, pretty much every single thing broke.

**Comment by juhanurmi** [comment]
A full Ahmia upgrade is coming: ahmia-index with Elasticsearch 8; ahmia-crawler with Scarpy2.11; and ahmia-site with Django5.

I will continue updating code across ahmia-site, ahmia-crawler, and ahmia-site.
